In [1]:
import pandas as  pd

In [2]:
data = {
    "review":[
        "I LOVE this movie!!!",
        "Worst film ever... waste of time",
        "It was okay, nothing special",
        "Amazing acting and great story",
        "Terrible movie, I hated it"
    ],
    "sentiment":[
        "positive",
        "negative",
        "neutral",
        "positive",
        "negative"
    ]
}

df = pd.DataFrame(data)

In [3]:
df

                             review sentiment
0              I LOVE this movie!!!  positive
1  Worst film ever... waste of time  negative
2      It was okay, nothing special   neutral
3    Amazing acting and great story  positive
4        Terrible movie, I hated it  negative

In [4]:
import re

In [5]:
def clean_text(text):

    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text)

    return text

In [6]:
clean_text("OMG!!! This is BAD 123 😡")

'omg this is bad '

In [7]:
df['clean_review'] = df['review'].apply(clean_text)

In [8]:
df

                             review sentiment                    clean_review
0              I LOVE this movie!!!  positive               i love this movie
1  Worst film ever... waste of time  negative   worst film ever waste of time
2      It was okay, nothing special   neutral     it was okay nothing special
3    Amazing acting and great story  positive  amazing acting and great story
4        Terrible movie, I hated it  negative       terrible movie i hated it

In [9]:
df.head()

                             review sentiment                    clean_review
0              I LOVE this movie!!!  positive               i love this movie
1  Worst film ever... waste of time  negative   worst film ever waste of time
2      It was okay, nothing special   neutral     it was okay nothing special
3    Amazing acting and great story  positive  amazing acting and great story
4        Terrible movie, I hated it  negative       terrible movie i hated it

In [10]:
df[["review", "clean_review"]]

                             review                    clean_review
0              I LOVE this movie!!!               i love this movie
1  Worst film ever... waste of time   worst film ever waste of time
2      It was okay, nothing special     it was okay nothing special
3    Amazing acting and great story  amazing acting and great story
4        Terrible movie, I hated it       terrible movie i hated it

In [11]:
df["tokens"] = df['clean_review'].apply(lambda x: x.split())

In [12]:
df

,review,sentiment,clean_review,tokens
0,I LOVE this movie!!!,positive,i love this movie,"[i, love, this, movie]"
1,Worst film ever... waste of time,negative,worst film ever waste of time,"[worst, film, ever, waste, of, time]"
2,"It was okay, nothing special",neutral,it was okay nothing special,"[it, was, okay, nothing, special]"
3,Amazing acting and great story,positive,amazing acting and great story,"[amazing, acting, and, great, story]"
4,"Terrible movie, I hated it",negative,terrible movie i hated it,"[terrible, movie, i, hated, it]"

In [14]:
df[['clean_review','tokens']]

                     clean_review                                tokens
0               i love this movie                [i, love, this, movie]
1   worst film ever waste of time  [worst, film, ever, waste, of, time]
2     it was okay nothing special     [it, was, okay, nothing, special]
3  amazing acting and great story  [amazing, acting, and, great, story]
4       terrible movie i hated it       [terrible, movie, i, hated, it]